### ISSUE TITLE
Full support for EcoSmart 60-Watt Equivalent Smart Hubspace A19 Color Changing CEC LED Light Bulb

### ISSUE THREAD

**Issue by kdurigan** [jdeath/Hubspace-Homeassistant#28]
The above bulb shows up as a non-color light in HA and does not support advanced rainbow effect.

Here is the link to the bulb: https://www.homedepot.com/p/EcoSmart-60-Watt-Equivalent-Smart-Hubspace-A19-Color-Changing-CEC-LED-Light-Bulb-with-Voice-Control-1-Bulb-11A19060WRGBWH1/318411935

Let me know if you need help testing.  BTW, these bulbs are $8.00 at Home Depot so a nice device to add inexpensively to your home.

**Comment by jdeath** [comment]
Should be supported now. Got confused because had two requests from different people wanting support for very similer models. Try setting the freindlyname.  Also, try without setting any freindlyname. I think @dloveall auto scanning code should have picked it up.

Download the latest light.py. If you confirm it works, I'll do a release.

No plans to support effects. Maybe @dloveall autoscanning code will add that feature.

**Comment by jdeath** [comment]
Closing as should be in latest release. Can all make a service to send the rainbow effect. Reopen if it does not work.
