### ISSUE TITLE
slow reaction time from HA to light

### ISSUE THREAD

**Issue by josh-m-sharpe** [jdeath/Hubspace-Homeassistant#32]
First off - I'm super impressed with how easy this was to set up (my first HACS/community plugin) - congrats, job well done!

I'm guessing this is more a hubspace/internet problem than this plugin, but can't hurt to ask.

I have several RGB 4" Lights.  I've added them to a Home Assistant Group.

I've noticed that when I make any change to the group (or an individual light) there is a noticeable delay in the change.  1-5 seconds.  This is especially noticeable when I change something (color/brightness/on/off) in the group because there are 4 lights to change - and they seemingly update in series.  So there can be a 10+ second delay in altering the final light.

Wondering if there are any tips and tricks you've learned to help speed up the round trip between HA and the light changing. 

Thank you!

**Comment by jdeath** [comment]
The reason it is slow is because it is a cloud integration. It sends a command to the hubspace servers (which I had to reverse engineer), then the servers relay it to your light.  I use something called synchronous calls, perhaps asynchronous calls would help. Problem is, I do not know python (learned by googling python), so I do not know any tricks to speed it up. Glad it works for you, but it is a stop-gap until someone figures out a better solution. Some people are trying to make this better, if you have ideas please submit a PR.

**Comment by Expl0dingBanana** [comment]
Can you test with #86 and see if this solves your issue?

During testing, you will move the repo to `https://github.com/Expl0dingBanana/Hubspace-Homeassistant`. Once the PR is merged, you will need to move it back to this @jdeath 's repo.

**Comment by Expl0dingBanana** [comment]
I believe this has been resolved with 3.0. Please re-open the issue if the problem persists
