### ISSUE TITLE
Time to read and devices

### ISSUE THREAD

**Issue by mohammadnouritani** [jdeath/Hubspace-Homeassistant#34]
So I have two requests 

first one is the time to read what is the state is about 120 sec 

the delay on sending the request is 1 to 2 sec and that is fine but if I want to do automation that start if a lamp is on it is taking 120 sec to run the automation can we do anything about that 

also all the devices show as entities can we also show them as devices  and that would be the second request thank you great job so far

**Comment by jdeath** [comment]
This is because it polls the cloud every 60s to get the state of the light. It should only take 60s to update, not sure why takes 120. try the new light.py I posted and see if it reduces to 60s . It will never get better than 60s. 

I am not sure how to add them as devices. Feel free to make a PR to add this capability.

**Comment by mohammadnouritani** [comment]
if I use google api sdk I am getting the automation to run within sec or 2 I don't know it feels like there is something to do about that delay thank you for your response I will try to add them as devices if I got it to work I will do  a pull request
